#!/bin/sh -eux

REPO=$(jq -r ".repository.full_name" "${GITHUB_EVENT_PATH}")
BRANCH=""

if [ -z "${BRANCH}" ]; then
  echo "No branch defined, Using ${GITHUB_REF}"
  BRANCH="${GITHUB_REF}"
fi

cd "${GITHUB_WORKSPACE}"

BASE_URI="https://api.github.com"
API_HEADER="Accept: application/vnd.github.v3+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

git config --global user.email "submodule@github.com"
git config --global user.name "GitHub Scheduled Submodules Action"

git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git

git fetch --all -p
git checkout "${BRANCH}"

git submodule init
git submodule update
git submodule foreach 'git fetch --all -p'
git submodule foreach 'git merge origin/master'
git add -v .
git commit -m "bumping submodules"
git push origin "${BRANCH}"
